#pragma once

// Paste isi file PEM CA certificate di bawah ini.
// Contoh: salin isi dari c:\mqtt\ca.crt apa adanya, termasuk
// -----BEGIN CERTIFICATE----- dan -----END CERTIFICATE-----
static const char MQTT_CA_CERT[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIICtTCCAZ0CFFiHrahZxCJyDHcATl0lXr2i8b3+MA0GCSqGSIb3DQEBCwUAMBcx
FTATBgNVBAMMDDQ1LjEyNi40My4zNTAeFw0yNjAzMjYxOTMzNDZaFw0yNzAzMjYx
OTMzNDZaMBcxFTATBgNVBAMMDDQ1LjEyNi40My4zNTCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBAL/0mCKXb0REYg42VvPOsK3SVjmub9IHTfqfmzWeo+JY
npC9rw7lq+cF5QlhlE6z+5JcPyHwa2PLCWgPuUS8cjaSbVbD6XvCXpN/NahvcQxm
RnNyKp3ZYZeIujLGVEQ4qaymv/gUMzVFEWvoxdvMdu0yqNqSOAa3G/B3P24x+UpQ
1RQ9RYyddhY8u1odQEt9MDpt7ntW29vjLXbwYIHZWOQ9ueh/KjP8H1JOjEylHsam
MLHRgg/tIrOX7/gjBTg1XSxHMUTO51kWuAdidHCqOAdU66Zsw0OOrjD9vcNPnR2+
MQtazFi4HZrpPutNHdlVnRfF/TZ3fdjZV1O5b1Oz06sCAwEAATANBgkqhkiG9w0B
AQsFAAOCAQEAPmcsFS80LWfclz/dUx47sPXLST+7heOB7g18CNc+/8i2+HBbtlMF
UUF0yTgxxX000zRqTZb8bKN1+SaaIWxLtRoDrf+kFf9cUpPKkaGD20nFG9H3MdLZ
chaXCL+c1tv3pSLEjTmOfQf65hRw9ysMwCKpADBg3GMFtDq2EQlinrUvqwvKff9Z
Lv7ew1QbSJwUib8wBkpNnQb9QuVyPzd/8eMDey8Y4vF4WsXT5gSHnpe/uv6Ylumo
1/GCzkbmT7eAyNfvGjzBratmw1l/g+VSb+Ul3S7A8cI+G9x2Fueyzm8I/o9drNyK
E+OmAbCJ+HYwSUZWvTLDQf7lMZgclSTsFg==
-----END CERTIFICATE-----
)EOF";
